---
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package:
    name: "{{ package }}"
    state: "{{ package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

# gkaio
- name: Deploy docker.service (template)
  template:
    src:   templates/docker.service.j2
    dest:  /etc/systemd/system/docker.service
    owner: vagrant
    group: root
    mode:  0775
  notify: restart docker daemon

#  - name: restart docker daemon
#    command: '{{ item }}'
#    with_items:
#    - systemctl daemon-reload
#    - systemctl enable docker
#    - systemctl restart docker

- include_tasks: docker-compose.yml
  when: install_compose

- include_tasks: docker-users.yml
  when: users
