---

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
edition: 'ce'
package: "docker-{{ edition }}"
package_state: present

# Service options.
service_state: started
service_enabled: true
restart_handler_state: restarted
opts: ''
network_address: "{{ VM.network.private.address }}"

# Docker Compose options.
install_compose: true
compose_version: "1.22.0"
compose_path: /usr/local/bin/docker-compose

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
apt_release_channel: stable
apt_arch: amd64
apt_repository: "deb [arch={{ apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ apt_release_channel }}"
apt_ignore_key_error: true

# Used only for RedHat/CentOS/Fedora.
yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-{{ edition }}.repo
yum_repo_enable_edge: 0
yum_repo_enable_test: 0

# A list of users who will be added to the docker group.
users: ['vagrant']
