---
- name: restart docker
  service: "name=docker state={{ restart_handler_state }}"

- name: restart docker daemon
  command: '{{ item }}'
  with_items:
  - systemctl daemon-reload
  - systemctl enable docker
  - systemctl restart docker
